remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Alternate Resources for Federal Data]
description: [This page hosts links to archived historical United States federal data as well as alternate non-government sources for health and social related data.]
